<?php

// Require
require_once '/usr/share/php/Psr/Container/autoload.php';

// Suggest

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'invoker\\callableresolver' => '/CallableResolver.php',
                'invoker\\exception\\invocationexception' => '/Exception/InvocationException.php',
                'invoker\\exception\\notcallableexception' => '/Exception/NotCallableException.php',
                'invoker\\exception\\notenoughparametersexception' => '/Exception/NotEnoughParametersException.php',
                'invoker\\invoker' => '/Invoker.php',
                'invoker\\invokerinterface' => '/InvokerInterface.php',
                'invoker\\parameterresolver\\associativearrayresolver' => '/ParameterResolver/AssociativeArrayResolver.php',
                'invoker\\parameterresolver\\container\\parameternamecontainerresolver' => '/ParameterResolver/Container/ParameterNameContainerResolver.php',
                'invoker\\parameterresolver\\container\\typehintcontainerresolver' => '/ParameterResolver/Container/TypeHintContainerResolver.php',
                'invoker\\parameterresolver\\defaultvalueresolver' => '/ParameterResolver/DefaultValueResolver.php',
                'invoker\\parameterresolver\\numericarrayresolver' => '/ParameterResolver/NumericArrayResolver.php',
                'invoker\\parameterresolver\\parameterresolver' => '/ParameterResolver/ParameterResolver.php',
                'invoker\\parameterresolver\\resolverchain' => '/ParameterResolver/ResolverChain.php',
                'invoker\\parameterresolver\\typehintresolver' => '/ParameterResolver/TypeHintResolver.php',
                'invoker\\reflection\\callablereflection' => '/Reflection/CallableReflection.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd

// Files
